[[server]]
name = "mediaserver-prod"
description = "the one that lives under my desk."
tags = ["git-sync"]
[server.config]
address = "https://host.docker.internal:8120"
enabled = true

##

[[stack]]
name = "adguard-dns"
tags = ["git-sync"]
[stack.config]
server = "mediaserver-prod"
auto_update = true
auto_update_all_services = true
git_account = "aadhithbala"
repo = "aadhithbala/HomeLab"
run_directory = "mediaserver-prod/dns"
file_paths = ["docker-compose.yml"]

##

[[stack]]
name = "arr-stack"
tags = ["git-sync"]
[stack.config]
server = "mediaserver-prod"
auto_update = true
auto_update_all_services = true
git_account = "aadhithbala"
repo = "aadhithbala/HomeLab"
run_directory = "mediaserver-prod/arr-stack"
file_paths = ["docker-compose.yml"]

##

[[stack]]
name = "backups"
tags = ["git-sync"]
[stack.config]
server = "mediaserver-prod"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "aadhithbala"
repo = "aadhithbala/HomeLab"
run_directory = "mediaserver-prod/backups"
file_paths = ["docker-compose.yml"]

##

[[stack]]
name = "dashboard"
tags = ["git-sync"]
[stack.config]
server = "mediaserver-prod"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "aadhithbala"
repo = "aadhithbala/HomeLab"
run_directory = "mediaserver-prod/dashboard"
file_paths = ["docker-compose.yml"]

##

[[stack]]
name = "home-assistant"
tags = ["git-sync"]
[stack.config]
server = "mediaserver-prod"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "aadhithbala"
repo = "aadhithbala/HomeLab"
run_directory = "mediaserver-prod/home-assistant"
file_paths = ["docker-compose.yml"]

##

[[stack]]
name = "komodo"
tags = ["git-sync"]
[stack.config]
server = "mediaserver-prod"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "aadhithbala"
repo = "aadhithbala/HomeLab"
run_directory = "mediaserver-prod/komodo"
file_paths = ["mongo.compose.yaml"]
env_file_path = "compose.env"
environment = """
COMPOSE_KOMODO_IMAGE_TAG=latest
COMPOSE_LOGGING_DRIVER=local # Enable log rotation with the local driver.
KOMODO_DB_USERNAME=[[KOMODO_DB_USERNAME]]
KOMODO_DB_PASSWORD=[[KOMODO_DB_PASSWORD]]
KOMODO_PASSKEY=[[KOMODO_PASSKEY]]
TZ=Asia/Calcutta
KOMODO_HOST=https://komodo.mediaserver.gleeze.com
KOMODO_TITLE=Komodo
KOMODO_FIRST_SERVER=https://host.docker.internal:8120
KOMODO_DISABLE_CONFIRM_DIALOG=true
KOMODO_MONITORING_INTERVAL="15-sec"
KOMODO_RESOURCE_POLL_INTERVAL="5-min"
KOMODO_LOCAL_AUTH=true
KOMODO_DISABLE_USER_REGISTRATION=false
KOMODO_ENABLE_NEW_USERS=false
KOMODO_DISABLE_NON_ADMIN_CREATE=false
KOMODO_TRANSPARENT_MODE=false
KOMODO_JWT_TTL="1-day"
KOMODO_OIDC_ENABLED=false
KOMODO_GITHUB_OAUTH_ENABLED=false
KOMODO_GOOGLE_OAUTH_ENABLED=false
KOMODO_AWS_ACCESS_KEY_ID= # Alt: KOMODO_AWS_ACCESS_KEY_ID_FILE
KOMODO_AWS_SECRET_ACCESS_KEY= # Alt: KOMODO_AWS_SECRET_ACCESS_KEY_FILE
PERIPHERY_ROOT_DIRECTORY=/etc/komodo
PERIPHERY_PASSKEYS=[[KOMODO_PASSKEY]]
PERIPHERY_DISABLE_TERMINALS=false
PERIPHERY_SSL_ENABLED=true
PERIPHERY_INCLUDE_DISK_MOUNTS=/etc/hostname
"""

##

[[stack]]
name = "mediaserver"
tags = ["git-sync"]
[stack.config]
server = "mediaserver-prod"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "aadhithbala"
repo = "aadhithbala/HomeLab"
run_directory = "mediaserver-prod/mediaserver"
file_paths = ["docker-compose.yml"]

##

[[stack]]
name = "monitoring"
tags = ["git-sync"]
[stack.config]
server = "mediaserver-prod"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "aadhithbala"
repo = "aadhithbala/HomeLab"
run_directory = "mediaserver-prod/monitoring"
file_paths = ["docker-compose.yml"]
environment = """
BESZEL_PUBLIC_KEY=[[BESZEL_SSH_KEY]]
"""

##

[[stack]]
name = "reverse-proxy"
tags = ["git-sync"]
[stack.config]
server = "mediaserver-prod"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "aadhithbala"
repo = "aadhithbala/HomeLab"
run_directory = "mediaserver-prod/reverse-proxy"
file_paths = ["docker-compose.yml"]

##

[[stack]]
name = "streamystats"
tags = ["git-sync"]
[stack.config]
server = "mediaserver-prod"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "aadhithbala"
repo = "aadhithbala/HomeLab"
run_directory = "mediaserver-prod/streamystats"
file_paths = ["docker-compose.yml"]
environment = """
SECRET_KEY_BASE = [[SECRET_KEY_BASE]]
POSTGRES_USER = [[POSTGRES_USER]]
POSTGRES_PASSWORD = [[POSTGRES_PASSWORD]]
POSTGRES_DB = [[POSTGRES_DB]]
DB_URL = [[DB_URL]]
API_URL = [[API_URL]]
"""

##

[[stack]]
name = "torrent-client"
tags = ["git-sync"]
[stack.config]
server = "mediaserver-prod"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "aadhithbala"
repo = "aadhithbala/HomeLab"
run_directory = "mediaserver-prod/torrent-client"
file_paths = ["docker-compose.yml"]

##

[[resource_sync]]
name = "sync-to-git"
tags = ["git-sync"]
[resource_sync.config]
repo = "aadhithbala/HomeLab"
git_account = "aadhithbala"
resource_path = ["main.toml"]
managed = true
match_tags = ["git-sync"]