name: monitoring

services:
  # container and server monitoring
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - /docker/appdata/beszel/data:/beszel_data
    networks:
      - proxy

  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PORT: 45876
      KEY: "${BESZEL_PUBLIC_KEY}"

  peekaping:
    image: 0xfurai/peekaping-bundle-sqlite:latest
    container_name: peekaping
    restart: always
    environment:
      - DB_NAME=/app/data/peekaping.db
    volumes:
      - /docker/appdata/peekaping/data/sqlite:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy


networks:
  proxy:
    external: true

