name: monitoring

services:
  # container and server monitoring
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - /docker/appdata/beszel/data:/beszel_data
    networks:
      - proxy

  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PORT: 45876
      KEY: "${BESZEL_PUBLIC_KEY}}"

# service uptime monitoring
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma

    volumes:
      - /docker/appdata/uptime-kuma/:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - proxy

networks:
  proxy:
    external: true

