name: Deploy All Stacks via Docker Compose

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code
        run: |
          cd /home/headlessnick/HomeLab
          git pull origin main

      - name: Export BESZEL_PUBLIC_KEY
        run: echo "BESZEL_PUBLIC_KEY=${{ secrets.BESZEL_PUBLIC_KEY }}" >> $GITHUB_ENV

      - name: Deploy all Compose stacks
        run: |
          cd /home/headlessnick/HomeLab/mediaserver-prod

          # Loop over each subfolder that contains a docker-compose.yml
          for STACK_DIR in */
          do
            if [ -f "$STACK_DIR/docker-compose.yml" ]; then
              echo "⟳ Updating stack in $STACK_DIR"
              cd "$STACK_DIR"

              docker compose up -d

              # Back to mediaserver-prod root for next iteration
              cd ..
            else
              echo "⚠️  No docker-compose.yml in $STACK_DIR — skipping."
            fi
          done

      - name: Confirm Running Containers
        run: |
          echo "🛠  List of all running containers (Name → Image → Status):"
          docker ps --format "table {{.Names}}\t{{.Image}}\t{{.Status}}"

